### ISSUE TITLE
re-run script for every modify(add/del) new user v2ray??

### ISSUE THREAD

**Issue by malikshi** [quackerd/d2ray#1]
>To start over or to update the existing configuration. Simply change config.yml, rerun configure.py and restart the stack.

**Comment by quackerd** [comment]
Yeah you need to rerun the script and restart the stack everytime you change config.yml

**Comment by quackerd** [comment]
If you wanna persist user uuids make sure to either generate uuids yourself or write the auto generated uuid back to config.yml. There is a WIP to auto update config.yml with the auto generated uuids.
